---
version: "3.8"
services:
  api:
    build:
      context: .
      args:
      - AUTH0_DOMAIN="${AUTH0_DOMAIN}"
    image: api_laravel_php_hello-world:basic-authorization
    env_file:
      - .env
    ports:
      - 6060:6060
